version: 1.0

workflows:
  ios:
    name: Build iOS
    max_build_duration: 60
    environment:
      flutter: stable
      node: "14.16.0"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Run tests
        script: |
          npm test
      - name: Build iOS app
        script: |
          npx react-native run-ios --configuration Release
    artifacts:
      - build/ios/iphoneos/*.ipa
  android:
    name: Build Android
    max_build_duration: 60
    environment:
      flutter: stable
      node: "14.16.0"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Run tests
        script: |
          npm test
      - name: Build Android app
        script: |
          npx react-native run-android --variant release
    artifacts:
      - build/android/app/build/outputs/apk/release/*.apk
